import type { FlagExpression, InstructionDefinition, NumberExpression, Statement } from "./model.ts";
import { validateInstruction } from "./validate.ts";

/** Expand every source and flag policy from its represented meaning, without running any effects. */
export function describeInstruction(definition: InstructionDefinition): string {
  validateInstruction(definition);
  const lines: string[] = [];
  const changed = new Set<string>();
  function number(expr: NumberExpression, parameters: Readonly<Record<string, NumberExpression>> = {}): string {
    switch (expr.kind) {
      // Arguments are in the caller's scope: substitution happens once, never recursively by name.
      case "value": return Object.hasOwn(parameters, expr.name) ? number(parameters[expr.name]!) : expr.name;
      case "literal": return `${expr.value.toString(16).toUpperCase().padStart(expr.width / 4, "0")}:u${expr.width}`;
      case "extend": return `zeroExtend${expr.width}(${number(expr.value, parameters)})`;
      case "high-byte": return `highByte(${number(expr.value, parameters)})`;
      case "shift-left": case "shift-right":
        return `${expr.kind === "shift-left" ? "shiftLeft" : "shiftRight"}(${number(expr.value, parameters)}, ${flag(expr.incoming, parameters)})`;
      case "subtract": case "add-wrap": case "concat": {
        const operation = { subtract: "subtract", "add-wrap": "addWrap", concat: "concatHighLow" }[expr.kind];
        return `${operation}(${number(expr.left, parameters)}, ${number(expr.right, parameters)})`;
      }
    }
  }
  function flag(expr: FlagExpression, parameters: Readonly<Record<string, NumberExpression>>): string {
    switch (expr.kind) {
      case "flag-value": return expr.name;
      case "flag-literal": return expr.value ? "1:flag" : "0:flag";
      case "not": return `not(${flag(expr.value, parameters)})`;
      case "xor": return `xor(${flag(expr.left, parameters)}, ${flag(expr.right, parameters)})`;
      case "negative": case "low-bit": case "zero": case "even-parity":
        return `${{ negative: "topBit", "low-bit": "lowBit", zero: "isZero", "even-parity": "evenParity8" }[expr.kind]}(${number(expr.value, parameters)})`;
      case "borrow": case "half-borrow": case "subtract-overflow":
        return `${{ borrow: "borrow", "half-borrow": "halfBorrow4", "subtract-overflow": "subtractOverflow" }[expr.kind]}(${number(expr.left, parameters)}, ${number(expr.right, parameters)})`;
    }
  }
  function body(steps: readonly Statement[], indent = ""): void {
    const emit = (line: string): void => { lines.push(indent + line); };
    for (const step of steps) {
      switch (step.kind) {
        case "capture": emit(`${step.name} := ${number(step.value)}`); break;
        case "read-register": emit(`${step.name}:u${step.register.width} := read ${step.register.field.toUpperCase()}`); break;
        case "read-flag": emit(`${step.name}:flag := read ${step.flag.field.toUpperCase()}`); break;
        case "fetch-byte": emit(`${step.name}:u8 := fetch byte`); break;
        case "read-memory": emit(`${step.name}:u8 := read memory[${number(step.address)}]`); break;
        case "write-register": emit(`write ${step.register.field.toUpperCase()}:u${step.register.width} := ${number(step.value)}`); break;
        case "write-memory": emit(`write memory[${number(step.address)}] := ${number(step.value)}`); break;
        case "read-source":
          emit(`${step.name}:u${step.source.width} := source "${step.source.name}" {`);
          body(step.source.steps, indent + "  ");
          emit(`  yield ${number(step.source.result)}`);
          emit("}");
          break;
        case "update-flags":
          emit(`flags "${step.policy.name}" simultaneously {`);
          for (const update of step.policy.updates) {
            changed.add(update.flag.field);
            emit(`  ${update.flag.field.toUpperCase()} := ${flag(update.value, step.arguments)}`);
          }
          emit("} // Preserve unlisted flags.");
          break;
      }
    }
  }
  for (const [name, bits] of Object.entries(definition.inputs ?? {})) lines.push(`${name}:u${bits} := input`);
  body(definition.steps);
  const fields = definition.cpu.state.flags;
  const preserved = fields?.kind === "group" ? Object.entries(fields.fields)
    .filter(([name, field]) => field.kind === "flag" && !changed.has(name)).map(([name]) => name.toUpperCase()) : [];
  return `### ${definition.cpu.name} ${definition.name}\n\n${definition.explanation}\n\n\`\`\`text\n${lines.join("\n")}\n\`\`\`\n\n`
    + `Flags preserved throughout: ${preserved.length ? preserved.join(", ") : "none"}.\n`;
}

/** Reproducible review artifact; this is an expansion, not generated emulator code. */
export function describeInstructions(definitions: readonly InstructionDefinition[]): string {
  return `# Instruction definition examples

Generated by \`node scripts/describe-cpu-semantics.ts\` from
[the typed definitions](../../src/components/cpus/semantics/definitions.ts).
Edit those definitions and their explanations, then regenerate this document.
See the [representation contract](instruction-semantics.md) for primitive meanings,
validation, execution bindings, and current limits. The same definitions also
generate typed instruction bodies for the bounded CPU migration.

Bodies begin after opcode selection. Motorola memory unary bodies and memory
comparisons receive a resolved address from the existing decoder. Declared inputs
are captured before entry. Statements are
ordered. Captures are immutable; a source
block has its own scope. All expressions in one flag update are evaluated before
any of its assignments. On an effect failure, completed effects remain and no
later statement runs. See the contract for which bodies are bound to CPU opcodes;
MOV B,A remains an executable comparison sample outside the 8080 opcode table.

## Examples

${definitions.map(describeInstruction).join("\n")}`;
}
