"""The learning path, grouped for browsing and ordered for Previous/Next links."""

LESSON_GROUPS = [
    {
        "slug": "bits-and-memory",
        "title": "Bits, numbers, and memory",
        "summary": "Start with values and the places that hold them. No processor knowledge needed.",
        "lessons": [
            {"slug": "bits-and-numbers", "title": "Bits and numbers",
             "summary": "Toggle eight bits and connect binary, decimal, and hexadecimal."},
            {"slug": "byte-wraparound", "title": "What happens after 255?",
             "summary": "Add one to a byte and follow the carry when it wraps around."},
            {"slug": "memory", "title": "Where does a byte live?",
             "summary": "Choose an address, read its contents, and store a different byte."},
        ],
    },
    {
        "slug": "programming-the-8080",
        "title": "Programming the 8080",
        "summary": "Follow real instructions from a working register to decisions and loops.",
        "lessons": [
            {"slug": "register", "title": "A place to work: a register",
             "summary": "Move a byte between RAM and the accumulator."},
            {"slug": "add-one", "title": "Doing something with a byte",
             "summary": "Load, add, and store using real 8080 instructions."},
            {"slug": "program", "title": "What comes next?",
             "summary": "Connect instruction bytes to the program counter and the next step."},
            {"slug": "change-program", "title": "Change one byte, change the program",
             "summary": "Edit an instruction's operand and predict the new result."},
            {"slug": "jump", "title": "Taking a different path",
             "summary": "Change where execution goes with a jump."},
            {"slug": "loop", "title": "Going around again",
             "summary": "Jump backward and reuse the state left by the previous trip."},
            {"slug": "conditional-loop", "title": "Knowing when to stop",
             "summary": "Use the carry flag to decide whether to repeat."},
            {"slug": "countdown", "title": "Counting down",
             "summary": "Subtract, test zero, and stop after a chosen number of trips."},
            {"slug": "comparison", "title": "Choosing a stopping point",
             "summary": "Compare with a target while keeping the value in the accumulator."},
        ],
    },
    {
        "slug": "altair-panel-and-io",
        "title": "The Altair panel and I/O",
        "summary": "Enter a program with switches, let it run, and connect it to input and output.",
        "lessons": [
            {"slug": "altair-memory", "title": "Switches, lights, and memory",
             "summary": "Meet the Altair panel through EXAMINE and DEPOSIT."},
            {"slug": "altair-program", "title": "Entering your first program",
             "summary": "Deposit instruction bytes, check them, and execute the program."},
            {"slug": "altair-running", "title": "Letting the computer run",
             "summary": "Use RUN and STOP, then resume from the saved state."},
            {"slug": "altair-output", "title": "Sending a byte out",
             "summary": "Send the accumulator to a separate device with OUT."},
            {"slug": "altair-input", "title": "Receiving a byte",
             "summary": "Offer input, receive it with IN, and send it to the output device."},
            {"slug": "altair-polling", "title": "Waiting for a byte",
             "summary": "Check readiness in a loop and echo each arriving byte."},
        ],
    },
    {
        "slug": "text-buffers-and-subroutines",
        "title": "Text, buffers, and subroutines",
        "summary": "Turn bytes into text and build reusable routines on the 8080 with the Altair teaching view.",
        "lessons": [
            {"slug": "bytes-as-characters", "title": "Bytes can be letters",
             "summary": "Interpret a byte as ASCII, including spaces and control codes."},
            {"slug": "typing-to-the-computer", "title": "Typing to the computer",
             "summary": "Type characters and follow their journey to a text display."},
            {"slug": "a-different-reply", "title": "A different reply",
             "summary": "Compare a received character and choose whether to replace it."},
            {"slug": "printing-a-message", "title": "Printing a message",
             "summary": "Read through HL and count the bytes sent from RAM."},
            {"slug": "where-does-a-message-end", "title": "Where does a message end?",
             "summary": "Use a zero terminator to mark the end of a message."},
            {"slug": "remembering-what-you-type", "title": "Remembering what you type",
             "summary": "Collect characters in a bounded RAM buffer, then print them."},
            {"slug": "remembering-where-to-return", "title": "Remembering where to return",
             "summary": "Call one routine twice and follow its return address on the stack."},
            {"slug": "a-routine-inside-a-routine", "title": "A routine inside a routine",
             "summary": "Follow nested calls and two pending return addresses."},
            {"slug": "keeping-a-value-across-a-call", "title": "Keeping a value across a call",
             "summary": "Preserve HL with PUSH and POP while a routine uses the pointer."},
        ],
    },
]
