import assert from "node:assert/strict";
import { test } from "node:test";
import { instructions as intel } from "../../../../src/components/cpus/generated/8080.js";
import type { Cpu8080State } from "../../../../src/components/cpus/semantics/generated/state/8080.js";
import type { ByteMemory } from "../../../../src/components/cpus/memory-access.js";
import { bodiesZ80 as zilog } from "../../../helpers/z80-bodies.js";
import { initialState, flagPattern } from "../z80/helpers.js";

const registers = [["B", "b"], ["C", "c"], ["D", "d"], ["E", "e"], ["H", "h"], ["L", "l"], ["A", "a"]] as const;
const cpus = [
  { name: "8080", updates: ["s", "z", "p", "ac"], forms: [
    { registers: [intel[0x04], intel[0x0c], intel[0x14], intel[0x1c], intel[0x24], intel[0x2c], intel[0x3c]],
      memory: (state: Cpu8080State, _address: number, context: ByteMemory) => intel[0x34](state, context) },
    { registers: [intel[0x05], intel[0x0d], intel[0x15], intel[0x1d], intel[0x25], intel[0x2d], intel[0x3d]],
      memory: (state: Cpu8080State, _address: number, context: ByteMemory) => intel[0x35](state, context) },
  ] },
  { name: "Z80", updates: ["s", "z", "h", "pv", "n"], forms: (["inc", "dec"] as const).map(name => ({
    registers: registers.map(([suffix]) => zilog[`${name}${suffix}`]), memory: zilog[`${name}Memory`],
  })) },
] as const;

// Extra fields also act as sentinels: each generated body may touch only its declared CPU fields.
function stateWithFlags(set: boolean) {
  return { ...initialState(), interruptEnabled: true,
    flags: { ...flagPattern(set ? 63 : 0), p: set, ac: set, cy: set } };
}

function expected(cpu: string, original: number, delta: number, flags: ReturnType<typeof stateWithFlags>["flags"]) {
  const result = (original + delta + 256) % 256;
  const low = original % 16 + delta, signed = (original < 128 ? original : original - 256) + delta;
  return { result, flags: { ...flags, s: result >= 128, z: result === 0, ...(cpu === "8080"
    ? { p: result.toString(2).replaceAll("0", "").length % 2 === 0, ac: delta === 1 ? low > 15 : low >= 0 }
    : { h: low < 0 || low > 15, pv: signed < -128 || signed > 127, n: delta === -1 }) } };
}

for (const { name, forms, updates } of cpus) {
  test(`${name} generated byte adjustments read once, preserve carry without reading it, and apply flags before register writeback`, () => {
    for (const [index, form] of forms.entries()) for (const [column, [, register]] of registers.entries()) {
      for (let original = 0; original < 256; original++) for (const set of [false, true]) {
        const state = stateWithFlags(set); state[register] = original;
        const before = structuredClone(state), flags = state.flags, events: string[] = [];
        state.flags = new Proxy(flags, {
          get() { assert.fail("Adjustments do not read any incoming flag"); },
          set(target, key, value) { assert.ok(updates.some(flag => flag === key)); events.push(`flag ${String(key)}`); return Reflect.set(target, key, value); },
        });
        const observed = new Proxy(state, {
          get(target, key, receiver) {
            if (key !== "flags") { assert.equal(key, register); events.push(`read ${register}`); }
            return Reflect.get(target, key, receiver);
          },
          set(target, key, value) { assert.equal(key, register); events.push(`write ${register}`); return Reflect.set(target, key, value); },
        });
        form.registers[column]!(observed);
        const result = expected(name, original, index === 0 ? 1 : -1, before.flags);
        assert.deepEqual({ ...state, flags }, { ...before, [register]: result.result, flags: result.flags });
        assert.deepEqual(events, [`read ${register}`, ...updates.map(flag => `flag ${flag}`), `write ${register}`]);
      }
    }
  });

  test(`${name} generated memory adjustments retain captured addresses, current flags, and exact failed read/write effects`, () => {
    for (const [index, form] of forms.entries()) for (const address of [0, 0xffff]) {
      for (const original of [0, 0x0f, 0x10, 0x7f, 0x80, 0xff]) for (const set of [false, true]) for (const failAt of ["none", "read", "write"]) {
        const state = { ...stateWithFlags(set), h: Math.floor(address / 256), l: address % 256 };
        const before = structuredClone(state), oldFlags = state.flags;
        const flags = stateWithFlags(!set).flags, result = expected(name, original, index === 0 ? 1 : -1, flags);
        const events: string[] = [], failure = new Error("adjustment access failure");
        const observed = new Proxy(state, {
          get(target, key, receiver) {
            if (name === "8080" && (key === "h" || key === "l")) events.push(`read ${key}`);
            else assert.equal(key, "flags");
            return Reflect.get(target, key, receiver);
          },
          set() { assert.fail("Resolved memory bodies do not change registers or replace flag storage"); },
        });
        const run = () => form.memory(observed, address, {
          readByte(actual) {
            assert.equal(actual, address); events.push("read");
            if (failAt === "read") throw failure;
            state.h = state.l = 0x55; state.ix = state.iy = 0x5555;
            state.flags = new Proxy(flags, {
              get() { assert.fail("No incoming flag reads"); },
              set(target, key, value) { assert.ok(updates.some(flag => flag === key)); events.push(`flag ${String(key)}`); return Reflect.set(target, key, value); },
            });
            return original;
          },
          writeByte(actual, value) {
            assert.equal(actual, address); assert.equal(value, result.result); assert.deepEqual(flags, result.flags);
            events.push("write"); if (failAt === "write") throw failure;
          },
        });
        if (failAt === "none") run(); else assert.throws(run, error => error === failure);
        assert.deepEqual(events, [...(name === "8080" ? ["read h", "read l"] : []), "read",
          ...(failAt === "read" ? [] : [...updates.map(flag => `flag ${flag}`), "write"])]);
        assert.deepEqual({ ...state, flags: failAt === "read" ? oldFlags : flags }, failAt === "read" ? before
          : { ...before, h: 0x55, l: 0x55, ix: 0x5555, iy: 0x5555, flags: result.flags });
        assert.deepEqual(oldFlags, before.flags);
      }
    }
  });
}
