// Each Markdown fence is parsed independently. Names, widths, encodings, and
// effects are validated by the chapter compiler, not by the editor grammar.
const commaSeparated = rule => seq(rule, repeat(seq(',', rule)));

module.exports = grammar({
  name: 'dromaios_cpu',
  extras: $ => [/\s/, $.comment],
  word: $ => $.identifier,
  // A local named pending can precede an operand write on the next line.
  conflicts: $ => [[$.pending_read, $._local_name]],

  rules: {
    source_file: $ => repeat(choice(
      $.cpu_declaration, $.state_declaration, $._state_field,
      $.source_declaration, $.action_declaration, $.policy_declaration,
      $.operands_declaration, $.codes_declaration, $.conditions_declaration,
      $.family_declaration, $.page_declaration, $.execution_declaration, $.reset_declaration, $.interface_declaration,
    )),

    cpu_declaration: $ => seq('cpu', field('model', $.string), optional(seq('boundary', 'segmented'))),
    state_declaration: $ => seq('state', '{', repeat(choice($._state_field, $.bank_declaration, $.group_declaration)), '}'),
    group_declaration: $ => seq('group', $._state_name, optional($.field_mapping), '{', repeat($._state_field), '}'),
    bank_declaration: $ => seq('bank', $._state_name, optional($.field_mapping), '{', repeat(choice($.register_declaration, $.flag_declaration)), '}'),
    _state_field: $ => choice($.register_declaration, $.array_declaration, $.flag_declaration, $.choice_declaration),
    register_declaration: $ => seq('register', $._state_name, ':', $.number, optional($.field_mapping)),
    array_declaration: $ => seq('array', $._state_name, ':', $.number, '[', $.number, ']', optional($.field_mapping)),
    flag_declaration: $ => seq(choice('flag', 'latch'), $._state_name, optional($.field_mapping)),
    choice_declaration: $ => seq('choice', $._state_name, ':', commaSeparated(choice($.string, $.number)), optional($.field_mapping)),
    field_mapping: $ => seq('=', $.identifier),

    source_declaration: $ => seq(choice('source', 'view'), field('name', $.identifier), $.string, optional($.parameters), ':', $.number, $.body),
    action_declaration: $ => seq('action', field('name', $.identifier), $.string, optional($.parameters), optional(seq('using', commaSeparated(choice('memory', 'boundary', 'staging', 'alignment')))), $.body),
    policy_declaration: $ => seq('policy', field('name', $.identifier), $.string, $.parameters,
      '{', repeat($.flag_update), '}'),
    parameters: $ => seq('(', optional(commaSeparated($.parameter)), ')'),
    parameter: $ => seq($.identifier, ':', choice($.number, 'flag')),
    flag_update: $ => seq($._state_name, '=', $._expression),

    operands_declaration: $ => seq('operands', field('name', $.identifier), '{', repeat($.operand_entry), '}'),
    operand_entry: $ => seq($.number, $.string, '=', choice(
      seq('register', $._state_name), seq('pair', $._state_name, $._state_name), seq(choice('memory', 'value'), $.identifier),
      seq('view', $.identifier, 'write', $.identifier), 'unsupported',
    )),
    codes_declaration: $ => seq('codes', field('name', $.identifier), optional(seq(':', $.number)),
      '{', repeat($.code_entry), '}'),
    code_entry: $ => seq($.number, $.string, optional(seq('=', $.number))),
    conditions_declaration: $ => seq('conditions', field('name', $.identifier), '{', repeat($.condition_entry), '}'),
    condition_entry: $ => seq($.number, $.string, '=', 'flag', $._state_name, '=', $.number),

    page_declaration: $ => seq('page', field('name', $.identifier), '=', $.number,
      optional(seq('on', $.identifier)), optional(seq('{', repeat($.page_capture), $.page_opcode, '}'))),
    page_capture: $ => seq($.identifier, ':', $.number, '=', 'read'),
    page_opcode: _ => seq('opcode', '=', choice('fetch', 'read')),
    family_declaration: $ => seq('family', field('name', $.identifier), optional($.parameters), choice(
      seq($._encoding, $.body),
      seq('{', repeat1($.encoding_declaration), repeat($._statement), '}'),
    )),
    encoding_declaration: $ => seq('encoding', $._encoding),
    _encoding: $ => seq(field('pattern', $.string),
      optional(seq('on', $.identifier)),
      optional(seq('for', commaSeparated($.selector))),
      optional(seq('with', commaSeparated($.source_binding))),
      optional(seq('named', $.string)),
      optional(seq('except', commaSeparated($.string))),
    ),
    selector: $ => seq($.identifier, 'in', $.identifier, optional(seq('.', field('view', $.identifier)))),
    source_binding: $ => seq($.identifier, '=', choice($.identifier, seq('register', $._state_name))),

    body: $ => seq('{', repeat($._statement), '}'),
    _statement: $ => choice(
      $.choose_capture, $.match_capture, $.match_statement, $.capture, $.write, $.apply_statement, $.exchange_statement, $.perform_statement, $.when_statement,
      $.iterate_capture, $.iterate_statement, $.divide_capture, $.reject_statement, $.return_statement, $.fault_statement, $.commit_statement, $.defer_statement, $.notify_statement, $.report_statement, $.escape_statement, $.target_statement, $.reset_statement, $.stage_statement,
    ),
    choose_capture: $ => seq(field('name', $._local_name), '=', 'choose', $._expression, ':', $.number,
      '{', 'then', $.body, 'else', $.body, '}'),
    match_capture: $ => seq(field('name', $._local_name), '=', 'match', $._expression, ':', $.number,
      '{', repeat1($.match_case), 'otherwise', 'unsupported', '}'),
    match_statement: $ => seq('match', $._expression, '{', repeat1($.match_case), 'otherwise', 'unsupported', '}'),
    match_case: $ => seq('case', field('pattern', $.string), optional(seq('for', commaSeparated($.selector))), $.body),
    iterate_capture: $ => seq(field('name', $._local_name), '=', 'iterate', $.arguments, $.body),
    iterate_statement: $ => seq('iterate', '(', $._expression, ')', '{', repeat1($.iteration_value),
      'step', '{', repeat($._statement), repeat1($.next_value), '}', '}'),
    iteration_value: $ => seq(field('name', $._local_name), ':', choice($.number, 'flag'), '=', $._expression),
    next_value: $ => seq('next', field('name', $._local_name), '=', $._expression),
    divide_capture: $ => seq(field('quotient', $._local_name), ',', field('remainder', $._local_name), optional(seq(',', field('overflow', $._local_name))), '=', 'divide',
      '(', $._expression, ',', $._expression, ',', choice('signed', 'unsigned'), ')', 'otherwise', $.string),
    reject_statement: $ => seq('reject', $.string, optional(seq('if', $._expression))),
    capture: $ => seq(field('name', $._local_name), '=', choice($._read, $._expression)),
    _read: $ => choice(
      seq('fetch', optional('word')), seq('next', 'address'), $.pending_read, seq('program', 'memory', $.arguments), seq('sample', 'test'), $.choice_read, $.state_read, $.array_read, $.source_read, $.operand_read,
    ),
    pending_read: $ => seq('pending', choice(seq('register', $._state_name), $.operand_read)),
    choice_read: $ => seq('choice', $._state_name, '=', choice($.string, $.number)),
    state_read: $ => seq(choice('register', 'flag', 'latch'), $._state_name),
    array_read: $ => seq('array', $._state_name, '[', $._expression, ']'),
    source_read: $ => seq('source', field('name', $.identifier), optional($.arguments)),
    operand_read: $ => seq('operand', $.identifier),
    write: $ => seq(choice($._state_name, $.array_target, $.operand_target, $.memory_target), '<-', choice($._expression, $.string)),
    array_target: $ => seq($._state_name, '[', optional($._expression), ']'),
    operand_target: $ => seq('operand', $.identifier),
    memory_target: $ => seq(choice('memory', 'port'), '(', $._expression, ')'),
    apply_statement: $ => seq(choice('apply', 'replace'), field('name', $.identifier), $.arguments),
    exchange_statement: $ => seq('exchange', $._state_name, ',', $._state_name),
    perform_statement: $ => seq('perform', field('name', $.identifier), $.arguments),
    when_statement: $ => seq('when', choice(seq('test', $.identifier), $._expression), $.body),
    return_statement: $ => seq('return', $._expression),
    fault_statement: $ => seq('fault', 'alignment', optional('program'), choice('read', 'write', 'fetch'),
      '(', $._expression, ')', 'if', $._expression),
    target_statement: $ => seq('select', 'target', '(', $._expression, ')'),
    reset_statement: _ => seq('reset', 'devices'),
    stage_statement: $ => seq('stage', choice($._state_name, seq('operand', $.identifier)), '<-', $._expression),
    commit_statement: _ => seq('commit', 'addresses'),
    defer_statement: _ => seq('defer', choice('irq', 'intr', 'all')),
    notify_statement: _ => seq('notify', 'reti'),
    report_statement: $ => seq('report', 'interrupt', $.arguments),
    escape_statement: $ => seq('send', 'escape', $.arguments, optional(seq('with', 'memory', $.arguments))),
    _local_name: $ => choice($.identifier, ...['exchange', 'port', 'next', 'reset', 'select', 'target', 'stage', 'pending', 'staging'].map(word => alias(word, $.identifier))),
    _expression: $ => choice($._local_name, $.number, $.call),
    call: $ => seq(field('function', $._local_name), $.arguments),
    arguments: $ => seq('(', optional(commaSeparated($._expression)), ')'),

    reset_declaration: $ => seq('reset', '{', repeat(choice(
      seq('attempt', 'action', $.identifier), seq('complete', 'action', $.identifier, 'with', 'failure'),
    )), '}'),
    execution_declaration: $ => seq('execution', optional(choice('segmented', 'word')), '{', repeat(choice(
      $.word_execution_policy, $.memory_policy, $.counter_policy, $.stopped_policy, $.word_policy,
      $.segmentation_policy, $.prefix_policy, $.waiting_policy, $.pending_policy, $.fault_delivery_policy, $.unsupported_policy,
      $.opcode_policy, $.operand_policy, $.failure_policy, $.action_policy, $.retirement_policy, $.notification_policy, $.interrupt_policy,
    )), '}'),
    word_execution_policy: $ => choice(
      seq('fetch', choice('big', 'little'), 'advance', 'after', 'word'), seq('alignment', $.number),
      seq('terminal', $._state_name), seq('fetched', 'action', $.identifier),
      seq('trace', $._state_name, 'pending', $._state_name, 'exception', $.string, 'action', $.identifier),
      seq('address', 'source', $.identifier), seq(choice('unknown', 'unsupported'), $.string),
      seq('inputs', '{', repeat(seq($.identifier, '=', $.string)), '}'),
      seq('exceptions', '{', repeat(seq($.string, 'vector', $.number, optional(seq('plus', $.string)), choice('complete', 'restart'))), '}'),
    ),
    segmentation_policy: $ => choice(seq('segment', $._state_name, 'shift', $.number),
      seq('record', 'address', $._state_name), seq('fetch', 'action', $.identifier)),
    prefix_policy: $ => seq('prefixes', 'limit', $.number, '{', repeat(choice(
      seq('segment', $.number, $._state_name), seq('repeat', $.number, $.number), seq('ignore', $.number),
    )), '}'),
    waiting_policy: $ => seq('waiting', $._state_name, 'with', $.call),
    pending_policy: $ => seq('pending', $.string, 'vector', $.number, 'when', $._state_name,
      'unless', $._state_name, 'with', $.identifier, 'then', $.identifier),
    fault_delivery_policy: $ => seq('fault', $.string, 'vector', $.number, 'with', $.identifier),
    unsupported_policy: _ => seq('unsupported', 'restore', 'counter'),
    memory_policy: $ => seq('memory', $.number),
    counter_policy: $ => seq('counter', $._state_name, optional(seq('write', $.identifier))),
    stopped_policy: $ => seq('stopped', choice('none', seq(choice($._state_name,
      seq('choice', $._state_name, 'unless', $.string)), optional(seq('as', 'waiting'))))),
    word_policy: _ => seq('word', choice('little', 'big')),
    opcode_policy: $ => seq('opcode', 'advance', 'on', choice('dispatch', 'read', seq('decode', 'with', 'action', $.identifier))),
    operand_policy: _ => seq('operand', 'advance', 'after', 'read'),
    failure_policy: _ => seq('failure', 'retain'),
    action_policy: $ => seq(choice('reset', 'retire'), choice('none', seq('action', $.identifier, optional(seq('sampling', commaSeparated(seq(choice('flag', 'latch'), $._state_name))))))),
    retirement_policy: $ => seq('retire', 'irq', 'into', $._state_name, optional(seq('then', 'action', $.identifier))),
    notification_policy: _ => seq('notify', 'reti', 'after', 'retire'),
    interrupt_policy: $ => seq('interrupt', choice('external', seq('offers', '{', repeat($.vector_offer), '}'), seq('entries', '{', repeat($.interrupt_entry), '}'), seq(optional('vectors'), '{', repeat(choice(
      $.vector_entry,
      $.accept_policy, $.bytes_policy, $.callback_policy, $.interrupt_counter_policy, $.unknown_policy,
    )), '}'))),
    vector_offer: $ => seq('source', $.identifier, choice('acknowledge', seq('vector', $.number)), '{', repeat(choice($.entry_gate, $.entry_action)), '}'),
    interrupt_entry: $ => seq('source', $.identifier, optional('acknowledge'), '{', repeat(choice(
      $.entry_gate, $.entry_action, $.entry_selection,
    )), '}'),
    entry_gate: $ => seq(choice('when', 'unless'), choice('latch', 'flag'), $._state_name, 'otherwise', $.string),
    entry_action: $ => seq(choice('accept', 'enter'), 'action', $.identifier),
    entry_selection: $ => seq('select', $._state_name, '{', repeat($.entry_case), '}'),
    entry_case: $ => seq('case', choice($.number, $.string), choice('supplied', seq('action', $.identifier, optional(seq('sampling', commaSeparated(seq(choice('flag', 'latch'), $._state_name))))))),
    vector_entry: $ => seq('source', $.identifier, choice('always', seq('unless', 'flag', $._state_name),
      seq('when', 'latch', $._state_name, 'otherwise', $.string)), 'with', $.call,
      optional(seq('resume', 'when', 'choice', $._state_name, '=', $.string, 'with', $.call))),
    accept_policy: $ => seq('accept', choice('always',
      seq('when', $._state_name, optional(seq('unless', $._state_name)))), 'with', $.identifier),
    callback_policy: _ => seq('callback', 'validate', 'on', choice('offer', 'read')),
    bytes_policy: _ => seq('bytes', 'acknowledge'),
    interrupt_counter_policy: _ => seq('counter', choice('preserve', 'advance')),
    unknown_policy: _ => seq('unknown', 'retain'),
    interface_declaration: $ => seq('interface', field('name', $.identifier), $.string,
      '{', repeat(choice($.snapshot_declaration, $.bank_alias)), '}'),
    snapshot_declaration: $ => seq('snapshot', $.identifier, optional(seq('.', $.identifier)), '=', $._state_name),

    bank_alias: $ => seq('bank', $.identifier, '=', $.identifier, 'snapshot', $.identifier),

    // State symbols are syntactically distinct from captured values in queries.
    // Accept unknown/lowercase names so incomplete edits still retain structure.
    _state_name: $ => seq(alias($.identifier, $.state_identifier), optional(seq('.', alias($.identifier, $.state_identifier)))),
    identifier: _ => /[A-Za-z][A-Za-z0-9_]*/,
    number: _ => token(choice(/[0-9]+/, /\$[0-9a-fA-F]+/)),
    string: $ => seq('"', repeat(choice($.string_content, $.escape_sequence)), '"'),
    // Keep // inside a string from winning over its next content segment.
    string_content: _ => token.immediate(prec(1, /[^"\\\r\n]+/)),
    escape_sequence: _ => token.immediate(seq('\\', choice(/["\\/bfnrt]/, /u[0-9a-fA-F]{4}/))),
    comment: _ => token(seq('//', /[^\r\n]*/)),
  },
});
